# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := framework Tut\ 01\ Main Tut\ 02\ Fragment\ Position Tut\ 02\ Vertex\ Colors Tut\ 03\ CPU\ Position\ Offset Tut\ 03\ Shader\ Position\ Offset Tut\ 03\ Shader\ Calc\ Offset Tut\ 03\ Fragment\ Change\ Color Tut\ 04\ Orthographic\ Cube Tut\ 04\ ShaderPerspective Tut\ 04\ MatrixPerspective Tut\ 04\ AspectRatio Tut\ 05\ Overlap\ No\ Depth Tut\ 05\ Base\ Vertex\ with\ Overlap Tut\ 05\ Depth\ Buffering Tut\ 05\ Vertex\ Clipping Tut\ 05\ Depth\ Clamping Tut\ 05\ Depth\ Fighting Tut\ 06\ Translation Tut\ 06\ Scale Tut\ 06\ Rotations Tut\ 06\ Hierarchy Tut\ 07\ World\ Scene Tut\ 07\ World\ With\ UBO Tut\ 08\ Gimbal\ Lock Tut\ 08\ Quaternion\ YPR Tut\ 08\ Camera\ Relative Tut\ 08\ Interpolation Tut\ 09\ Basic\ Lighting Tut\ 09\ Scale\ and\ Lighting Tut\ 09\ Ambient\ Lighting Tut\ 10\ Vertex\ Point\ Lighting Tut\ 10\ Fragment\ Point\ Lighting Tut\ 10\ Fragment\ Attenuation Tut\ 11\ Phong\ Lighting Tut\ 11\ Blinn\ vs\ Phong\ Lighting Tut\ 11\ Gaussian\ Specular\ Lighting Tut\ 12\ Scene\ Lighting Tut\ 12\ HDR\ Lighting Tut\ 12\ Gamma\ Correction Tut\ 13\ Basic\ Impostor Tut\ 13\ Geometry\ Impostor Tut\ 14\ Basic\ Texture Tut\ 14\ Perspective\ Interpolation Tut\ 14\ Material\ Texture Tut\ 15\ Many\ Images Tut\ 16\ Gamma\ Ramp Tut\ 16\ Gamma\ Checkers Tut\ 16\ Gamma\ Landscape

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

framework: 
	@echo "==== Building framework ($(config)) ===="
	@${MAKE} --no-print-directory -C framework -f Makefile

Tut\ 01\ Main: framework
	@echo "==== Building Tut 01 Main ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 01\ Hello\ Triangle -f Makefile

Tut\ 02\ Fragment\ Position: framework
	@echo "==== Building Tut 02 Fragment Position ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 02\ Playing\ with\ Colors -f Tut\ 02\ Fragment\ Position.make

Tut\ 02\ Vertex\ Colors: framework
	@echo "==== Building Tut 02 Vertex Colors ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 02\ Playing\ with\ Colors -f Tut\ 02\ Vertex\ Colors.make

Tut\ 03\ CPU\ Position\ Offset: framework
	@echo "==== Building Tut 03 CPU Position Offset ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ CPU\ Position\ Offset.make

Tut\ 03\ Shader\ Position\ Offset: framework
	@echo "==== Building Tut 03 Shader Position Offset ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ Shader\ Position\ Offset.make

Tut\ 03\ Shader\ Calc\ Offset: framework
	@echo "==== Building Tut 03 Shader Calc Offset ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ Shader\ Calc\ Offset.make

Tut\ 03\ Fragment\ Change\ Color: framework
	@echo "==== Building Tut 03 Fragment Change Color ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ Fragment\ Change\ Color.make

Tut\ 04\ Orthographic\ Cube: framework
	@echo "==== Building Tut 04 Orthographic Cube ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ Orthographic\ Cube.make

Tut\ 04\ ShaderPerspective: framework
	@echo "==== Building Tut 04 ShaderPerspective ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ ShaderPerspective.make

Tut\ 04\ MatrixPerspective: framework
	@echo "==== Building Tut 04 MatrixPerspective ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ MatrixPerspective.make

Tut\ 04\ AspectRatio: framework
	@echo "==== Building Tut 04 AspectRatio ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ AspectRatio.make

Tut\ 05\ Overlap\ No\ Depth: framework
	@echo "==== Building Tut 05 Overlap No Depth ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Overlap\ No\ Depth.make

Tut\ 05\ Base\ Vertex\ with\ Overlap: framework
	@echo "==== Building Tut 05 Base Vertex with Overlap ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Base\ Vertex\ with\ Overlap.make

Tut\ 05\ Depth\ Buffering: framework
	@echo "==== Building Tut 05 Depth Buffering ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Depth\ Buffering.make

Tut\ 05\ Vertex\ Clipping: framework
	@echo "==== Building Tut 05 Vertex Clipping ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Vertex\ Clipping.make

Tut\ 05\ Depth\ Clamping: framework
	@echo "==== Building Tut 05 Depth Clamping ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Depth\ Clamping.make

Tut\ 05\ Depth\ Fighting: framework
	@echo "==== Building Tut 05 Depth Fighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Depth\ Fighting.make

Tut\ 06\ Translation: framework
	@echo "==== Building Tut 06 Translation ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Translation.make

Tut\ 06\ Scale: framework
	@echo "==== Building Tut 06 Scale ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Scale.make

Tut\ 06\ Rotations: framework
	@echo "==== Building Tut 06 Rotations ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Rotations.make

Tut\ 06\ Hierarchy: framework
	@echo "==== Building Tut 06 Hierarchy ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Hierarchy.make

Tut\ 07\ World\ Scene: framework
	@echo "==== Building Tut 07 World Scene ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 07\ World\ in\ Motion -f Tut\ 07\ World\ Scene.make

Tut\ 07\ World\ With\ UBO: framework
	@echo "==== Building Tut 07 World With UBO ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 07\ World\ in\ Motion -f Tut\ 07\ World\ With\ UBO.make

Tut\ 08\ Gimbal\ Lock: framework
	@echo "==== Building Tut 08 Gimbal Lock ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Gimbal\ Lock.make

Tut\ 08\ Quaternion\ YPR: framework
	@echo "==== Building Tut 08 Quaternion YPR ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Quaternion\ YPR.make

Tut\ 08\ Camera\ Relative: framework
	@echo "==== Building Tut 08 Camera Relative ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Camera\ Relative.make

Tut\ 08\ Interpolation: framework
	@echo "==== Building Tut 08 Interpolation ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Interpolation.make

Tut\ 09\ Basic\ Lighting: framework
	@echo "==== Building Tut 09 Basic Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 09\ Lights\ on -f Tut\ 09\ Basic\ Lighting.make

Tut\ 09\ Scale\ and\ Lighting: framework
	@echo "==== Building Tut 09 Scale and Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 09\ Lights\ on -f Tut\ 09\ Scale\ and\ Lighting.make

Tut\ 09\ Ambient\ Lighting: framework
	@echo "==== Building Tut 09 Ambient Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 09\ Lights\ on -f Tut\ 09\ Ambient\ Lighting.make

Tut\ 10\ Vertex\ Point\ Lighting: framework
	@echo "==== Building Tut 10 Vertex Point Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 10\ Plane\ Lights -f Tut\ 10\ Vertex\ Point\ Lighting.make

Tut\ 10\ Fragment\ Point\ Lighting: framework
	@echo "==== Building Tut 10 Fragment Point Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 10\ Plane\ Lights -f Tut\ 10\ Fragment\ Point\ Lighting.make

Tut\ 10\ Fragment\ Attenuation: framework
	@echo "==== Building Tut 10 Fragment Attenuation ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 10\ Plane\ Lights -f Tut\ 10\ Fragment\ Attenuation.make

Tut\ 11\ Phong\ Lighting: framework
	@echo "==== Building Tut 11 Phong Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 11\ Shinies -f Tut\ 11\ Phong\ Lighting.make

Tut\ 11\ Blinn\ vs\ Phong\ Lighting: framework
	@echo "==== Building Tut 11 Blinn vs Phong Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 11\ Shinies -f Tut\ 11\ Blinn\ vs\ Phong\ Lighting.make

Tut\ 11\ Gaussian\ Specular\ Lighting: framework
	@echo "==== Building Tut 11 Gaussian Specular Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 11\ Shinies -f Tut\ 11\ Gaussian\ Specular\ Lighting.make

Tut\ 12\ Scene\ Lighting: framework
	@echo "==== Building Tut 12 Scene Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 12\ Dynamic\ Range -f Tut\ 12\ Scene\ Lighting.make

Tut\ 12\ HDR\ Lighting: framework
	@echo "==== Building Tut 12 HDR Lighting ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 12\ Dynamic\ Range -f Tut\ 12\ HDR\ Lighting.make

Tut\ 12\ Gamma\ Correction: framework
	@echo "==== Building Tut 12 Gamma Correction ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 12\ Dynamic\ Range -f Tut\ 12\ Gamma\ Correction.make

Tut\ 13\ Basic\ Impostor: framework
	@echo "==== Building Tut 13 Basic Impostor ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 13\ Impostors -f Tut\ 13\ Basic\ Impostor.make

Tut\ 13\ Geometry\ Impostor: framework
	@echo "==== Building Tut 13 Geometry Impostor ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 13\ Impostors -f Tut\ 13\ Geometry\ Impostor.make

Tut\ 14\ Basic\ Texture: framework
	@echo "==== Building Tut 14 Basic Texture ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 14\ Textures\ Are\ Not\ Pictures -f Tut\ 14\ Basic\ Texture.make

Tut\ 14\ Perspective\ Interpolation: framework
	@echo "==== Building Tut 14 Perspective Interpolation ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 14\ Textures\ Are\ Not\ Pictures -f Tut\ 14\ Perspective\ Interpolation.make

Tut\ 14\ Material\ Texture: framework
	@echo "==== Building Tut 14 Material Texture ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 14\ Textures\ Are\ Not\ Pictures -f Tut\ 14\ Material\ Texture.make

Tut\ 15\ Many\ Images: framework
	@echo "==== Building Tut 15 Many Images ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 15\ Many\ Images -f Makefile

Tut\ 16\ Gamma\ Ramp: framework
	@echo "==== Building Tut 16 Gamma Ramp ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 16\ Gamma\ and\ Textures -f Tut\ 16\ Gamma\ Ramp.make

Tut\ 16\ Gamma\ Checkers: framework
	@echo "==== Building Tut 16 Gamma Checkers ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 16\ Gamma\ and\ Textures -f Tut\ 16\ Gamma\ Checkers.make

Tut\ 16\ Gamma\ Landscape: framework
	@echo "==== Building Tut 16 Gamma Landscape ($(config)) ===="
	@${MAKE} --no-print-directory -C Tut\ 16\ Gamma\ and\ Textures -f Tut\ 16\ Gamma\ Landscape.make

clean:
	@${MAKE} --no-print-directory -C framework -f Makefile clean
	@${MAKE} --no-print-directory -C Tut\ 01\ Hello\ Triangle -f Makefile clean
	@${MAKE} --no-print-directory -C Tut\ 02\ Playing\ with\ Colors -f Tut\ 02\ Fragment\ Position.make clean
	@${MAKE} --no-print-directory -C Tut\ 02\ Playing\ with\ Colors -f Tut\ 02\ Vertex\ Colors.make clean
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ CPU\ Position\ Offset.make clean
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ Shader\ Position\ Offset.make clean
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ Shader\ Calc\ Offset.make clean
	@${MAKE} --no-print-directory -C Tut\ 03\ OpenGLs\ Moving\ Triangle -f Tut\ 03\ Fragment\ Change\ Color.make clean
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ Orthographic\ Cube.make clean
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ ShaderPerspective.make clean
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ MatrixPerspective.make clean
	@${MAKE} --no-print-directory -C Tut\ 04\ Objects\ at\ Rest -f Tut\ 04\ AspectRatio.make clean
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Overlap\ No\ Depth.make clean
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Base\ Vertex\ with\ Overlap.make clean
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Depth\ Buffering.make clean
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Vertex\ Clipping.make clean
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Depth\ Clamping.make clean
	@${MAKE} --no-print-directory -C Tut\ 05\ Objects\ in\ Depth -f Tut\ 05\ Depth\ Fighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Translation.make clean
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Scale.make clean
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Rotations.make clean
	@${MAKE} --no-print-directory -C Tut\ 06\ Objects\ in\ Motion -f Tut\ 06\ Hierarchy.make clean
	@${MAKE} --no-print-directory -C Tut\ 07\ World\ in\ Motion -f Tut\ 07\ World\ Scene.make clean
	@${MAKE} --no-print-directory -C Tut\ 07\ World\ in\ Motion -f Tut\ 07\ World\ With\ UBO.make clean
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Gimbal\ Lock.make clean
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Quaternion\ YPR.make clean
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Camera\ Relative.make clean
	@${MAKE} --no-print-directory -C Tut\ 08\ Getting\ Oriented -f Tut\ 08\ Interpolation.make clean
	@${MAKE} --no-print-directory -C Tut\ 09\ Lights\ on -f Tut\ 09\ Basic\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 09\ Lights\ on -f Tut\ 09\ Scale\ and\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 09\ Lights\ on -f Tut\ 09\ Ambient\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 10\ Plane\ Lights -f Tut\ 10\ Vertex\ Point\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 10\ Plane\ Lights -f Tut\ 10\ Fragment\ Point\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 10\ Plane\ Lights -f Tut\ 10\ Fragment\ Attenuation.make clean
	@${MAKE} --no-print-directory -C Tut\ 11\ Shinies -f Tut\ 11\ Phong\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 11\ Shinies -f Tut\ 11\ Blinn\ vs\ Phong\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 11\ Shinies -f Tut\ 11\ Gaussian\ Specular\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 12\ Dynamic\ Range -f Tut\ 12\ Scene\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 12\ Dynamic\ Range -f Tut\ 12\ HDR\ Lighting.make clean
	@${MAKE} --no-print-directory -C Tut\ 12\ Dynamic\ Range -f Tut\ 12\ Gamma\ Correction.make clean
	@${MAKE} --no-print-directory -C Tut\ 13\ Impostors -f Tut\ 13\ Basic\ Impostor.make clean
	@${MAKE} --no-print-directory -C Tut\ 13\ Impostors -f Tut\ 13\ Geometry\ Impostor.make clean
	@${MAKE} --no-print-directory -C Tut\ 14\ Textures\ Are\ Not\ Pictures -f Tut\ 14\ Basic\ Texture.make clean
	@${MAKE} --no-print-directory -C Tut\ 14\ Textures\ Are\ Not\ Pictures -f Tut\ 14\ Perspective\ Interpolation.make clean
	@${MAKE} --no-print-directory -C Tut\ 14\ Textures\ Are\ Not\ Pictures -f Tut\ 14\ Material\ Texture.make clean
	@${MAKE} --no-print-directory -C Tut\ 15\ Many\ Images -f Makefile clean
	@${MAKE} --no-print-directory -C Tut\ 16\ Gamma\ and\ Textures -f Tut\ 16\ Gamma\ Ramp.make clean
	@${MAKE} --no-print-directory -C Tut\ 16\ Gamma\ and\ Textures -f Tut\ 16\ Gamma\ Checkers.make clean
	@${MAKE} --no-print-directory -C Tut\ 16\ Gamma\ and\ Textures -f Tut\ 16\ Gamma\ Landscape.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   framework"
	@echo "   Tut 01 Main"
	@echo "   Tut 02 Fragment Position"
	@echo "   Tut 02 Vertex Colors"
	@echo "   Tut 03 CPU Position Offset"
	@echo "   Tut 03 Shader Position Offset"
	@echo "   Tut 03 Shader Calc Offset"
	@echo "   Tut 03 Fragment Change Color"
	@echo "   Tut 04 Orthographic Cube"
	@echo "   Tut 04 ShaderPerspective"
	@echo "   Tut 04 MatrixPerspective"
	@echo "   Tut 04 AspectRatio"
	@echo "   Tut 05 Overlap No Depth"
	@echo "   Tut 05 Base Vertex with Overlap"
	@echo "   Tut 05 Depth Buffering"
	@echo "   Tut 05 Vertex Clipping"
	@echo "   Tut 05 Depth Clamping"
	@echo "   Tut 05 Depth Fighting"
	@echo "   Tut 06 Translation"
	@echo "   Tut 06 Scale"
	@echo "   Tut 06 Rotations"
	@echo "   Tut 06 Hierarchy"
	@echo "   Tut 07 World Scene"
	@echo "   Tut 07 World With UBO"
	@echo "   Tut 08 Gimbal Lock"
	@echo "   Tut 08 Quaternion YPR"
	@echo "   Tut 08 Camera Relative"
	@echo "   Tut 08 Interpolation"
	@echo "   Tut 09 Basic Lighting"
	@echo "   Tut 09 Scale and Lighting"
	@echo "   Tut 09 Ambient Lighting"
	@echo "   Tut 10 Vertex Point Lighting"
	@echo "   Tut 10 Fragment Point Lighting"
	@echo "   Tut 10 Fragment Attenuation"
	@echo "   Tut 11 Phong Lighting"
	@echo "   Tut 11 Blinn vs Phong Lighting"
	@echo "   Tut 11 Gaussian Specular Lighting"
	@echo "   Tut 12 Scene Lighting"
	@echo "   Tut 12 HDR Lighting"
	@echo "   Tut 12 Gamma Correction"
	@echo "   Tut 13 Basic Impostor"
	@echo "   Tut 13 Geometry Impostor"
	@echo "   Tut 14 Basic Texture"
	@echo "   Tut 14 Perspective Interpolation"
	@echo "   Tut 14 Material Texture"
	@echo "   Tut 15 Many Images"
	@echo "   Tut 16 Gamma Ramp"
	@echo "   Tut 16 Gamma Checkers"
	@echo "   Tut 16 Gamma Landscape"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
